services:
  # Payment Service
  payment-service:
    image: payment-service:0.1
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    depends_on:
      - gateway-service

  # Gateway Service
  gateway-service:
    image: gateway-service:0.1
    ports:
      - "8082:9090"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

  # Redis
  redis:
    container_name: redis-container
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

networks:
  mynetwork:


volumes:
  redis_data:


