spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:postgresql://containers-us-west-48.railway.app:5953/railway
    username: postgres
    password: CHANGE_ME
  flyway:
    url: jdbc:postgresql://containers-us-west-48.railway.app:5953/railway
    user: postgres
    password: CHANGE_ME

logging:
  pattern:
    console: "%highlight{[%-5level]} %cyan(%d{yyyy-MM-dd HH:mm:ss.SSS}) %yellow([%t]) %magenta(%logger{36}) - %msg%n"
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

server:
  port: 8081
